#!/usr/bin/env bash
set -euo pipefail

echo "==> Building asana-cli..."
go build -o asana-cli .

echo "==> Installing binary..."
go install .

echo "==> Installing Claude Code skill..."
SKILL_DIR="$HOME/.claude/skills/asana"
mkdir -p "$SKILL_DIR"
cp skill/SKILL.md "$SKILL_DIR/SKILL.md"
echo "    Skill installed to $SKILL_DIR"

echo ""
echo "==> Setup complete!"
echo ""
echo "============================================"
echo "  AUTHENTICATION SETUP"
echo "============================================"
echo ""
echo "You need three values (shared per team — only one person creates the OAuth app):"
echo ""
echo "  ASANA_CLIENT_ID      — from your Asana OAuth app"
echo "  ASANA_CLIENT_SECRET   — from your Asana OAuth app"
echo "  ASANA_WORKSPACE_ID    — your Asana workspace GID"
echo ""
echo "To create the OAuth app (only needed once per team):"
echo "  1. Go to https://app.asana.com/0/developer-console"
echo "  2. Create a new app"
echo "  3. Under OAuth > Permission scopes, toggle 'Full permissions'"
echo "  4. Set redirect URI to http://localhost:8931/callback"
echo "  5. Copy Client ID and Client Secret"
echo "  6. Share these with your team securely"
echo ""
echo "To find your Workspace GID:"
echo "  Open any Asana project in the browser — the URL looks like:"
echo "  https://app.asana.com/0/<workspace_gid>/..."
echo ""
echo "--------------------------------------------"
echo "  macOS / Linux — add to your shell config:"
echo "--------------------------------------------"
echo ""

# Detect shell
CURRENT_SHELL="$(basename "${SHELL:-bash}")"

if [ "$CURRENT_SHELL" = "fish" ]; then
    SHELL_CONFIG="~/.config/fish/config.fish"
    echo "  Detected shell: fish"
    echo "  Add these lines to $SHELL_CONFIG:"
    echo ""
    echo "    set -gx ASANA_CLIENT_ID \"your-client-id\""
    echo "    set -gx ASANA_CLIENT_SECRET \"your-client-secret\""
    echo "    set -gx ASANA_WORKSPACE_ID \"your-workspace-gid\""
    echo ""
    echo "  Then reload: source $SHELL_CONFIG"
elif [ "$CURRENT_SHELL" = "zsh" ]; then
    SHELL_CONFIG="~/.zshrc"
    echo "  Detected shell: zsh"
    echo "  Add these lines to $SHELL_CONFIG:"
    echo ""
    echo "    export ASANA_CLIENT_ID=\"your-client-id\""
    echo "    export ASANA_CLIENT_SECRET=\"your-client-secret\""
    echo "    export ASANA_WORKSPACE_ID=\"your-workspace-gid\""
    echo ""
    echo "  Then reload: source $SHELL_CONFIG"
else
    SHELL_CONFIG="~/.bashrc"
    echo "  Detected shell: bash"
    echo "  Add these lines to $SHELL_CONFIG:"
    echo ""
    echo "    export ASANA_CLIENT_ID=\"your-client-id\""
    echo "    export ASANA_CLIENT_SECRET=\"your-client-secret\""
    echo "    export ASANA_WORKSPACE_ID=\"your-workspace-gid\""
    echo ""
    echo "  Then reload: source $SHELL_CONFIG"
fi

echo ""
echo "--------------------------------------------"
echo "  Windows (PowerShell) — set permanently:"
echo "--------------------------------------------"
echo ""
echo "  Run these in PowerShell (sets system-wide for your user):"
echo ""
echo "    [System.Environment]::SetEnvironmentVariable('ASANA_CLIENT_ID', 'your-client-id', 'User')"
echo "    [System.Environment]::SetEnvironmentVariable('ASANA_CLIENT_SECRET', 'your-client-secret', 'User')"
echo "    [System.Environment]::SetEnvironmentVariable('ASANA_WORKSPACE_ID', 'your-workspace-gid', 'User')"
echo ""
echo "  Then restart your terminal."
echo ""
echo "============================================"
echo "  FINAL STEP"
echo "============================================"
echo ""
echo "  After setting env vars, run:"
echo ""
echo "    asana-cli auth login"
echo ""
echo "  This opens your browser to authorize. Then verify with:"
echo ""
echo "    asana-cli auth status"
echo ""
